"""The verbatim evidence span (SC6 graph edge half and excerpts; PLAN 8.11).

Page texts are synthetic (fixtures/pages, labeled, example.com URLs only,
decision 15) or generated by Hypothesis. Each test names, in its docstring,
the mutation that turns it red.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from hypothesis import assume, given, settings
from hypothesis import strategies as st

from agent import config
from agent.kg import HAS_CODE, KnowledgeGraph
from agent.nodes.research import build_sources
from agent.research.excerpts import excerpt_terms
from agent.rules.evidence import (
    NO_PAGE_TEXT, NOT_IN_PAGE, OK, SNIPPET_JOINER, TARGET_MISSING, TOO_LONG, TOO_SHORT,
    evidence_sha256, normalize_for_span, verify_span,
)
from agent.state import RunContext

PAGES = Path(__file__).resolve().parent / "fixtures" / "pages"
MANUAL = (PAGES / "optima_880_synthetic_manual.txt").read_bytes().decode("utf-8")
MANUAL_URL = "https://example.com/synthetic/sundance/optima-880-manual"
FLO_RAW = (PAGES / "flo_raw_synthetic.txt").read_bytes().decode("utf-8")
FLO_SNIPPET = (PAGES / "flo_snippet_synthetic.md").read_bytes().decode("utf-8").strip()
FLO_URL = "https://example.com/synthetic/spa/flo-formatting"
NOW = "2026-09-18T00:00:00+00:00"


def edge_fields(evidence: str, url: str = MANUAL_URL) -> dict[str, str]:
    return {"source_url": url, "retrieved_at": NOW, "evidence": evidence,
            "evidence_sha256": evidence_sha256(evidence), "brief_run_id": "run-evidence",
            "validated_at": NOW}


def test_normalization_is_exactly_nfc_and_listed_whitespace() -> None:
    """Mutation evidence_normalize_casefolds: normalize_for_span also casefolds."""
    assert normalize_for_span(" a\t\tb\r\n c\u00a0\u00a0d  ") == "a b c d"
    assert normalize_for_span("E\u0301") == "\u00c9"  # NFC composes
    for kept in ("FLO", "\u201cquoted\u201d", "a" + chr(0x2013) + "b", "\ufb01le", "soft\u00adhyphen", "a\u2009b"):
        assert normalize_for_span(kept) == kept


def test_edge_kept_only_with_verbatim_span(tmp_path: Path) -> None:
    """Mutation kg_rejected_edge_stored_unverified: try_add_edge stores a
    refused edge with verified=False instead of leaving it out."""
    g = KnowledgeGraph()
    series = g.add_family("Sundance Spas", "880 Series")
    flo = g.add_code("Sundance Spas", "880 Series", "FLO")
    good = "FLO: The heater senses no water flow."
    # The reason is checked too, so a span check that lets a span through is
    # not hidden by the later token check refusing it for another reason.
    cases = {
        "verbatim": (good, OK),
        "case_flipped": ("FLO: the heater senses no water flow.", NOT_IN_PAGE),
        "fuzzy_word": ("FLO: The heater detects no water flow.", NOT_IN_PAGE),
        "snippet_joined": ("FLO: The heater senses no water flow. [...] Rinse the filter", SNIPPET_JOINER),
        "no_target": ("The heater senses no water flow. Clean or replace", TARGET_MISSING),
        "too_short": ("FLO: The heater", TOO_SHORT),
    }
    for name, (evidence, reason) in cases.items():
        result = g.try_add_edge(HAS_CODE, series, flo, page_text=MANUAL, **edge_fields(evidence))
        assert (result.ok, result.reason) == (reason == OK, reason), name
    kept = g.edges()
    assert [e["evidence"] for e in kept] == [good]
    saved = tmp_path / "g.json"
    g.save(saved)
    text = saved.read_text(encoding="utf-8")
    assert "verified" not in text and "detects" not in text and "[...]" not in text
    assert len(json.loads(text)["edges"]) == 1


# Hypothesis page texts: words, the target, and every whitespace form 8.11 folds.
WORDS = st.sampled_from(["the", "heater", "Flow", "senses", "no", "water", "PUMP", "filter", "E10", "set",
                         "point.", "Clean", "cartridge,", "if", "clears", "(see", "page", "4)", "\u00e9t\u00e9"])
SPACES = st.sampled_from([" ", "  ", "\n", "\t", "\r\n", "\u00a0", " \n "])
TARGET = "FLO"


@st.composite
def page_and_span(draw):
    """A page with the target somewhere, and a raw substring of it that contains the target."""
    before = draw(st.lists(st.tuples(WORDS, SPACES), min_size=0, max_size=60))
    after = draw(st.lists(st.tuples(SPACES, WORDS), min_size=0, max_size=60))
    left = "".join(w + s for w, s in before)
    right = "".join(s + w for s, w in after)
    text = left + TARGET + right
    start = draw(st.integers(0, len(left)))
    end = draw(st.integers(len(left) + len(TARGET), len(text)))
    return text, text[start:end]


def _in_bounds(span: str) -> bool:
    return config.EVIDENCE_MIN_CHARS <= len(normalize_for_span(span)) <= config.EVIDENCE_MAX_CHARS


@settings(max_examples=300, deadline=None)
@given(data=page_and_span(), choice=st.data())
def test_evidence_span_property(data, choice) -> None:
    """Mutations evidence_match_casefold (spans compared case insensitively),
    evidence_normalize_casefolds, evidence_skip_joiner_check and
    evidence_skip_target_check: each lets a rejected span through."""
    text, span = data
    assume(_in_bounds(span))
    assert verify_span(span, text, target=TARGET) == verify_span(span, text, target=TARGET)
    assert verify_span(span, text, target=TARGET).ok, "a verbatim in bounds span with the target"
    norm_text, norm_span = normalize_for_span(text), normalize_for_span(span)

    # One non whitespace character changed.
    positions = [i for i, ch in enumerate(norm_span) if not ch.isspace()]
    i = choice.draw(st.sampled_from(positions))
    replacement = choice.draw(st.sampled_from("QXZqxz7#"))
    changed = norm_span[:i] + replacement + norm_span[i + 1:]
    assume(changed != norm_span and changed not in norm_text)
    assert not verify_span(changed, text, target=TARGET).ok

    # Case flipped on one cased character.
    cased = [i for i, ch in enumerate(norm_span) if ch.swapcase() != ch]
    j = choice.draw(st.sampled_from(cased))
    flipped = norm_span[:j] + norm_span[j].swapcase() + norm_span[j + 1:]
    assume(flipped not in norm_text)
    assert verify_span(flipped, text, target=TARGET).reason in (NOT_IN_PAGE, TARGET_MISSING)

    # Verbatim, but the page itself carries the snippet joiner inside the span.
    k = choice.draw(st.integers(0, len(norm_span)))
    joined_span = norm_span[:k] + " [...] " + norm_span[k:]
    joined_page = norm_text.replace(norm_span, joined_span, 1)
    if _in_bounds(joined_span) and TARGET in joined_span:
        assert verify_span(joined_span, joined_page, target=TARGET).reason == SNIPPET_JOINER

    # Found only in a snippet: the same words, but no raw text, or other raw text.
    assert verify_span(span, None, target=TARGET).reason == NO_PAGE_TEXT
    assert verify_span(span, "Synthetic page with other words entirely.", target=TARGET).reason == NOT_IN_PAGE

    # Missing the target: a span checked for a target it does not contain.
    assert verify_span(span, text, target="ZZTOP").reason == TARGET_MISSING


@settings(max_examples=200, deadline=None)
@given(start=st.integers(0, len(normalize_for_span(MANUAL))), length=st.integers(1, 460))
def test_evidence_span_bounds_on_a_fixture_page(start, length) -> None:
    """Mutation evidence_skip_length_check: condition 4 is not applied."""
    norm = normalize_for_span(MANUAL)
    span = norm[start:start + length].strip(" ")
    assume(TARGET in span)
    result = verify_span(span, MANUAL, target=TARGET)
    if len(span) < config.EVIDENCE_MIN_CHARS:
        assert result.reason == TOO_SHORT
    elif len(span) > config.EVIDENCE_MAX_CHARS:
        assert result.reason == TOO_LONG
    else:
        assert result.reason == OK


def _sentence_with(text: str, needle: str) -> str:
    for sentence in re.split(r"(?<=\.)\s+", text):
        if needle in sentence:
            return sentence
    raise AssertionError(f"no sentence with {needle!r}")


def test_quote_from_excerpt_verifies_when_snippet_formatting_differs(tmp_path: Path) -> None:
    """Mutation research_excerpts_from_snippet: build_sources cuts excerpts
    from the snippet (`content`) instead of `raw_content`."""
    ctx = RunContext(run_id="run-excerpt", mode="replay", ledger_path=tmp_path / "l.sqlite",
                     registry_path=tmp_path / "r.sqlite", graph_path=tmp_path / "g.json",
                     pages_dir=tmp_path / "pages")
    artifact = {"tool": "search", "results": [
        {"url": FLO_URL, "title": "Synthetic spa panel codes", "content": FLO_SNIPPET, "raw_content": FLO_RAW},
    ]}
    trail = [{"tool": "search", "query": "q", "n_results": 1, "credits": 1, "at": NOW, "status": "ok",
              "artifact": artifact, "pages": {}}]
    [source] = build_sources(ctx, [artifact], trail, set(),
                             excerpt_terms({"model": "Optima 880"}, "FLO", "hot tub not heating"))
    excerpt_quote = _sentence_with(" ".join(source["excerpts"]), "FLO")
    snippet_quote = _sentence_with(source["snippet"], "FLO")
    assert "**" in snippet_quote, "the snippet carries markdown the raw text lacks"
    assert verify_span(excerpt_quote, FLO_RAW, target="FLO").ok
    assert verify_span(snippet_quote, FLO_RAW, target="FLO").reason == NOT_IN_PAGE
    # The raw text was saved by its hash, so the page can be found again.
    assert (ctx.pages_dir / f"{source['text_sha256']}.txt").is_file()


def test_length_bounds_are_measured_after_normalization() -> None:
    """Mutation evidence_length_on_raw_span: condition 4 measures the raw span,
    so whitespace runs push a too short span over 20 characters and a 400
    character span over the limit.

    PLAN 8.11 condition 4 is read as measured on the normalized span.
    """
    short = "FLO: no water flow."  # 19 characters once normalized
    padded = short.replace(" ", "  \t ")
    assert len(normalize_for_span(padded)) == 19 and len(padded) > config.EVIDENCE_MIN_CHARS
    page = f"Synthetic page text. {padded} and more words after it."
    assert verify_span(padded, page, target=TARGET).reason == TOO_SHORT
    # Exactly the maximum once normalized, longer raw: it verifies.
    words = ["FLO"] + ["flow"] * 200
    norm = " ".join(words)[: config.EVIDENCE_MAX_CHARS].rstrip(" ")
    norm = norm + "x" * (config.EVIDENCE_MAX_CHARS - len(norm))
    raw = norm.replace(" ", " \n ")
    assert len(normalize_for_span(raw)) == config.EVIDENCE_MAX_CHARS < len(raw)
    long_page = f"Synthetic page text.\n{raw}\nEnd of the synthetic page."
    assert verify_span(raw, long_page, target=TARGET).reason == OK
    over = raw + "y"
    assert verify_span(over, long_page + over, target=TARGET).reason == TOO_LONG


# Synthetic page text in the shape of the Phase 5 live page: a markdown table
# whose code cell sits just before the meaning cell on the same line.
TABLE_PAGE = (
    "Synthetic error code table (synthetic, for tests).\n"
    "| Code | Meaning | Action |\n"
    "| E7 | Stands for sensor open. The heater stops until the sensor closes. | Call a technician. |\n"
    "| XE9 | Stands for a synthetic fault used to test token edges. | None. |\n"
    "E5\n"
    "Stands for high limit. The heater shuts off to protect the shell. | Let it cool. |\n"
    "| E3 | " + "Padding words that push the quote far away from its code. " + "Stands for low flow in the loop. |\n"
    "| E4 | XE4 label. Stands for a doubled label in one row. |\n"
)


def test_quote_widened_to_the_code_printed_just_before_it() -> None:
    """Mutations: evidence_anchor_any_line (a code on an earlier line is used);
    evidence_anchor_gap_unbounded (a code far before the quote is used);
    evidence_anchor_token_unchecked (a code inside a longer token is used)."""
    from agent.rules.evidence import anchor_to_target

    quote = "Stands for sensor open. The heater stops until the sensor closes."
    widened = anchor_to_target(quote, TABLE_PAGE, target="E7")
    assert widened == "E7 | Stands for sensor open. The heater stops until the sensor closes."
    assert verify_span(widened, TABLE_PAGE, target="E7").ok
    # Already names the code: nothing to widen.
    assert anchor_to_target("E7 | Stands for sensor open.", TABLE_PAGE, target="E7") is None
    # Not verbatim in the page: never widened.
    assert anchor_to_target("Stands for sensor opened.", TABLE_PAGE, target="E7") is None
    # The code is on the line before the quote.
    assert anchor_to_target("Stands for high limit. The heater shuts off to protect the shell.",
                            TABLE_PAGE, target="E5") is None
    # The code is on the same line but further back than the allowed gap.
    assert anchor_to_target("Stands for low flow in the loop.", TABLE_PAGE, target="E3") is None
    # The nearest "E4" before the quote is inside "XE4"; the standalone E4 further back anchors it.
    assert anchor_to_target("Stands for a doubled label in one row.", TABLE_PAGE, target="E4") == \
        "E4 | XE4 label. Stands for a doubled label in one row."
    # The only "E9" before the quote is inside the longer token "XE9".
    assert anchor_to_target("Stands for a synthetic fault used to test token edges.",
                            TABLE_PAGE, target="E9") is None


def test_persist_stores_the_widened_verbatim_span() -> None:
    """Mutation persist_widening_off: a quote that is verbatim but leaves out the
    code is dropped (the Phase 5 live run saved no edge this way)."""
    from agent.nodes import persist as persist_mod

    quote = "Stands for sensor open. The heater stops until the sensor closes."
    form, reason, evidence = persist_mod._printed_target("E7", quote, TABLE_PAGE, None)
    assert (form, reason) == ("E7", persist_mod.OK_WIDENED)
    assert evidence == "E7 | Stands for sensor open. The heater stops until the sensor closes."
    assert normalize_for_span(evidence) in normalize_for_span(TABLE_PAGE)
    form, reason, _ = persist_mod._printed_target("E5", "Stands for high limit.", TABLE_PAGE, None)
    assert form is None


# ---------------------------------------------------------------------------
# The cause condition (DOCUMENTED_CAUSE condition 5, decision D2)
# ---------------------------------------------------------------------------


def test_cause_words_are_letters_long_enough_casefolded_and_stemmed() -> None:
    """Mutations: evidence_cause_words_no_stem (a trailing s, ed or ing is kept,
    so "slows" and "slowed" differ); evidence_cause_words_keep_stop_words (stop
    list ignored); evidence_cause_words_short_words (words under
    CAUSE_WORD_MIN_CHARS count)."""
    from agent.rules.evidence import cause_words

    assert config.CAUSE_WORD_MIN_CHARS == 4 and "which" in config.CAUSE_STOP_WORDS
    words = cause_words("Filters CLOGGED; flow slowing, which the pump has")
    assert words == {"filter", "clogg", "flow", "slow", "pump"}
    assert cause_words("slows") == cause_words("slowed") == cause_words("slowing") == {"slow"}
    assert cause_words("E10 the fan is off; low set 4TTR") == set()  # digits end a word; short words dropped
    assert cause_words("that with from") == set()


def test_cause_condition_needs_two_shared_words_or_the_whole_label() -> None:
    """Mutations: evidence_cause_min_words_one (one shared content word is
    enough); evidence_cause_verbatim_label_ignored (a label printed whole in
    the span, with fewer than two content words, fails); evidence_cause_skips_page
    (verify_cause_span never checks the page text)."""
    from agent.rules.evidence import CAUSE_WORDS_MISSING, check_cause_shape, verify_cause_span

    assert config.CAUSE_MIN_SHARED_WORDS == 2
    span = "FLO: The heater senses no water flow."
    for label in ("The heater has no water flow.", "Heaters sensing flow", "water flows"):
        assert verify_cause_span(span, MANUAL, label=label).reason == OK, label
    # One shared content word ("flow") is not enough.
    assert check_cause_shape(span, label="Low flow alarm").reason == CAUSE_WORDS_MISSING
    # A short label printed whole in the span passes on the verbatim path.
    assert check_cause_shape("COOL: Water is 20 degrees below the set point.", label="set point").ok
    assert check_cause_shape("COOL: Water is 20 degrees below the set point.",
                             label="a set point").reason == CAUSE_WORDS_MISSING
    # Conditions 1 to 4 still hold for a cause.
    assert verify_cause_span(span, MANUAL.replace("water flow", "flow"), label="water flow").reason == NOT_IN_PAGE
    assert verify_cause_span(span, None, label="water flow").reason == NO_PAGE_TEXT
    assert check_cause_shape("water flow", label="water flow").reason == TOO_SHORT
    assert check_cause_shape("heater water flow [...] heater water flow", label="water flow").reason == SNIPPET_JOINER
    assert check_cause_shape(span, label="  ").ok is False


def test_cause_label_must_match_whole_words() -> None:
    """Mutation: cause_label_substring (the whole label path matches inside a
    longer word, so "heat" passes on "heater heats" and "low flow" on "slow
    flow"). Review finding E3."""
    from agent.rules.evidence import CAUSE_WORDS_MISSING, check_cause_shape

    assert check_cause_shape("The heater heats water.", label="heat").reason == CAUSE_WORDS_MISSING
    assert check_cause_shape("It runs slow flow on the day shift here.",
                             label="low flow").reason == CAUSE_WORDS_MISSING
    assert check_cause_shape("at low flow the heater stops", label="low flow").ok


def test_generic_cause_label_is_refused() -> None:
    """Mutation: cause_stop_list_short (troubleshooting filler such as "check"
    counts as a content word, so "Check the unit" is stored as a cause from
    any "check ... unit" sentence). Review finding E5."""
    from agent.rules.evidence import CAUSE_WORDS_MISSING, check_cause_shape, cause_words

    for word in ("check", "ensure", "sure", "please", "contact", "call", "need"):
        assert word in config.CAUSE_STOP_WORDS, word
    assert cause_words("checks checking needs calls") == set()
    assert check_cause_shape("check that the unit is plugged in and the breaker is on.",
                             label="Check the unit").reason == CAUSE_WORDS_MISSING
    # A real component fault keeps its content words: "display", "panel".
    assert check_cause_shape("The display panel has failed and shows nothing.",
                             label="Display panel failure").ok


def test_cause_component_only_quote_passes_known_limit() -> None:
    """Characterization of a known false positive of the D2 floor (review
    finding E2, an open question for Roanuk): a "<component> <failure>" label
    passes on a quote that only names the two word component, because two
    shared content words are enough. The quote below documents no failure.
    Mutation: evidence_cause_known_limit_min_words_three (the floor raised to
    three words, which this test would notice as a change of the decided rule)."""
    from agent.rules.evidence import check_cause_shape

    quote = "The ozone generator can be turned off from the service menu."
    assert check_cause_shape(quote, label="Ozone generator failure").ok
    assert check_cause_shape("Toggle the flow switch cover to reach the jets.", label="Flow switch stuck open").ok


# ---------------------------------------------------------------------------
# Word boundaries of a stored span (decision D3)
# ---------------------------------------------------------------------------

# Synthetic, shaped like the Phase 5 page row whose stored edge ended "filte".
CUT_PAGE = (
    "SYNTHETIC PAGE TEXT for tests (not a real document).\n"
    "| FLO | Stands for Flow Switch. The heater is deactivated and filter/circulation may stop. |\n"
    "The pump's seal leaks. Check the drain. The unit restarts.\n"
)


def test_stored_span_snaps_to_word_boundaries() -> None:
    """Mutations: evidence_snap_off (a span cut inside a word is kept as it is);
    evidence_snap_no_trim_end and evidence_snap_no_trim_start (a span too long to
    extend is refused instead of trimmed back); evidence_snap_ignores_max (the
    extended span may pass EVIDENCE_MAX_CHARS); evidence_snap_accept_ignored (a
    snapped span the caller's check refuses is returned); evidence_word_is_nonspace
    (a cut before a slash or period counts as inside a word);
    evidence_word_apostrophe_not_word (a cut between "pump'" and "s" is not seen);
    evidence_snap_max_exclusive (a span extended to exactly EVIDENCE_MAX_CHARS
    is refused)."""
    from agent.rules.evidence import snap_span_to_words

    ok = lambda span: True  # noqa: E731
    cut = "FLO | Stands for Flow Switch. The heater is deactivated and filte"
    assert snap_span_to_words(cut, CUT_PAGE, accept=ok) == \
        "FLO | Stands for Flow Switch. The heater is deactivated and filter"
    assert snap_span_to_words("ands for Flow Switch. The heater", CUT_PAGE, accept=ok) == \
        "Stands for Flow Switch. The heater"
    assert snap_span_to_words("The pump'", CUT_PAGE, accept=ok) == "The pump's"
    # Whole words already: returned unchanged, raw whitespace and all.
    for whole in ("FLO | Stands for Flow Switch.", "deactivated and filter", "Stands for  Flow\nSwitch"):
        assert snap_span_to_words(whole, CUT_PAGE, accept=ok) == whole
    # The caller's check refuses the extended span and the trimmed one: refused.
    assert snap_span_to_words(cut, CUT_PAGE, accept=lambda s: s.endswith("filte")) is None
    assert snap_span_to_words(cut, CUT_PAGE, accept=lambda s: not s.endswith("filter")) == \
        "FLO | Stands for Flow Switch. The heater is deactivated and"
    assert snap_span_to_words("no such text", CUT_PAGE, accept=ok) is None

    # Extending past EVIDENCE_MAX_CHARS trims the cut word back instead.
    long_word = "x" * 30
    page = " ".join(["alpha"] * 80) + " " + long_word + " end"
    tail_cut = page[page.index(long_word) + 5 - config.EVIDENCE_MAX_CHARS + 2: page.index(long_word) + 5]
    assert len(tail_cut) == config.EVIDENCE_MAX_CHARS - 2
    snapped = snap_span_to_words(tail_cut, page, accept=ok)
    assert snapped is not None and snapped.endswith("alpha") and len(snapped) <= config.EVIDENCE_MAX_CHARS
    assert snapped.startswith("alpha")
    head_page = "start " + long_word + " " + " ".join(["beta"] * 100)
    head_cut = head_page[len("start ") + 25: len("start ") + 25 + config.EVIDENCE_MAX_CHARS - 2]
    snapped = snap_span_to_words(head_cut, head_page, accept=ok)
    assert snapped is not None and snapped.startswith("beta") and len(snapped) <= config.EVIDENCE_MAX_CHARS

    # A span that is exactly EVIDENCE_MAX_CHARS once extended is kept whole
    # (evidence_snap_max_exclusive: a strict limit trims "valve" off, and the
    # cause check then refuses what is left).
    from agent.rules.evidence import verify_cause_span

    label = "The drain valves stick."
    limit_page = "Intro. " + "x" * (config.EVIDENCE_MAX_CHARS - 17) + " the drain valves stick..."
    start = limit_page.index("x")
    at_limit = limit_page[start: limit_page.index("valve") + len("valve")]
    assert len(at_limit) == config.EVIDENCE_MAX_CHARS - 1
    snapped = snap_span_to_words(at_limit, limit_page,
                                 accept=lambda span: verify_cause_span(span, limit_page, label=label).ok)
    assert snapped is not None and snapped.endswith("valves") and len(snapped) == config.EVIDENCE_MAX_CHARS
